version: '3.8'
services:
  ntlapi:
    image: bachhonglien/src-ntlapi:latest
    build:
      context: .
      dockerfile: NguyenTienLinh/Dockerfile

  ntlwebapp:
    image: bachhonglien/src-ntlwebapp:latest
    build:
      context: .
      dockerfile: WebApp/Dockerfile

#network section
networks:
  default:
    name: tana_networking
    driver: bridge

